const bgImages: { [key: number]: { [key: string]: any } } = {
    0: {
        sunrise: require('../assets/0_sunrise.png'),
        day: require('../assets/0_day.png'),
        sunset: require('../assets/0_sunset.png'),
        night: require('../assets/1_night.png'),
    },
    1: {
        sunrise: require('../assets/0_sunrise.png'),
        day: require('../assets/1_day.png'),
        sunset: require('../assets/0_sunset.png'),
        night: require('../assets/1_night.png'),
    },
    2: {
        sunrise: require('../assets/2_sunrise.png'),
        day: require('../assets/2_day.png'),
        sunset: require('../assets/2_sunset.png'),
        night: require('../assets/2_night.png'),
    },
    3: {
        sunrise: require('../assets/2_sunrise.png'),
        day: require('../assets/3_day.png'),
        sunset: require('../assets/2_sunset.png'),
        night: require('../assets/2_night.png'),
    },
    45: {
        sunrise: require('../assets/2_sunrise.png'),
        day: require('../assets/45_day.png'),
        sunset: require('../assets/2_sunset.png'),
        night: require('../assets/2_night.png'),
    },
    48: {
        sunrise: require('../assets/2_sunrise.png'),
        day: require('../assets/45_day.png'),
        sunset: require('../assets/2_sunset.png'),
        night: require('../assets/2_night.png'),
    },
    51: {
        sunrise: require('../assets/2_sunrise.png'),
        day: require('../assets/51_day.png'),
        sunset: require('../assets/2_sunset.png'),
        night: require('../assets/2_night.png'),
    },
    53: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/53_day.png'),
        sunset: require('../assets/53_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    55: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/55_day.png'),
        sunset: require('../assets/55_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    56: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/56_day.png'),
        sunset: require('../assets/53_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    57: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/57_day.png'),
        sunset: require('../assets/55_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    61: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/61_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/61_night.png'),
    },
    63: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/63_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    65: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/65_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    66: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/65_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    67: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/65_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    71: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/71_day.png'),
        sunset: require('../assets/55_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    73: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/73_day.png'),
        sunset: require('../assets/55_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    75: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/75_day.png'),
        sunset: require('../assets/55_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    77: {
        sunrise: require('../assets/53_sunrise.png'),
        day: require('../assets/77_day.png'),
        sunset: require('../assets/55_sunset.png'),
        night: require('../assets/53_night.png'),
    },
    80: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/80_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    81: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/63_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    82: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/82_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    85: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/61_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    86: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/61_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/63_night.png'),
    },
    95: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/95_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/95_night.png'),
    },
    96: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/96_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/95_night.png'),
    },
    99: {
        sunrise: require('../assets/61_sunrise.png'),
        day: require('../assets/99_day.png'),
        sunset: require('../assets/61_sunset.png'),
        night: require('../assets/95_night.png'),
    },
};

export default bgImages;
